#################################
## SERVER
#################################
http://api.giybatnoma.uz:8080
server.port=8080
#################################
## DATABASE
#################################
# Note: 'db' refers to the container name in docker-compose
spring.datasource.url=jdbc:postgresql://db:5432/giybat_db
spring.datasource.username=giybat_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#################################
## ATTACH
#################################
#attach.upload.folder=/home/ubuntu/images
#attach.url=https://api.giybatnoma.uz/api/v1/attach
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB
#################################
## MAIL SENDING
#################################
# Mail.ru SMTP Configuration (Port 465 SSL)
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=muzaffar-ortiqov@mail.ru
# Use a variable for the password
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtps

# SSL specific settings for Mail.ru
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.socketFactory.port=465
spring.mail.properties.mail.smtps.socketFactory.class=javax.net.ssl.SSLSocketFactory

# Connection Timeouts
spring.mail.properties.mail.smtps.connectiontimeout=10000
spring.mail.properties.mail.smtps.timeout=10000

