### Upload
POST localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTixST0xFX1VTRVIiLCJpZCI6ImJhNzY1YjJiLTUzZWItNDEwZi1hOTJjLWNhNDUxNjgxYmFlMSIsInN1YiI6Im11emFmZmFybWlrZTJAZ21haWwuY29tIiwiaWF0IjoxNzQ2MTY2MTAwLCJleHAiOjE3NDY3NzA5MDB9.VPeJBun5hvc2fSTa-69kT3C-pQ0QQkeD_iqx3c84fo8qxS7JAWuF2lr-3HMl89ztJul6dHo4-GZMnMXWKKWTSA

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zari.jpg"

< C:\Users\HP\Desktop\test\Images\zari.jpg

### Open file
GET localhost:8080/api/v1/attach/open/ba765b2b-53eb-410f-a92c-ca451681bae1.jpg