### Upload
POST localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiJiYmYyOTA0ZS1lZjA1LTQzYTMtYTFlZC1kYTcyZWY5YTRkY2YiLCJzdWIiOiJtdXphZmZhcm1pa2UyQGdtYWlsLmNvbSIsImlhdCI6MTc1Mjc1MTMyMCwiZXhwIjoxNzUzMzU2MTIwfQ.boA_dALN1O41-K2AhUo3sNI9tm1wVTqRnqoXh1ER5iRi5VY-DwKtObbVNQkmAq_sfHRJxiUJzTYu7IC51IRtJg

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sunflower.jpg"

< C:\Users\HP\Desktop\test\Images\sunflower.jpg

### Open file
GET localhost:8080/api/v1/attach/open/3652a057-1bb6-469b-a470-9a9944219846.jpg