### CREATE
POST localhost:8080/api/v1/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxOGM2MjJhOC04ZTJjLTQ1MmUtYWJjOS1hYjk2MDUxZTVlNzQiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzY4MjI4LCJleHAiOjE3NDQ5NzMwMjh9.I2RFeL2dKAvJCx6xVLIm6lXfHoB1G7q55-JvwWS-ONRTBcuy35qUTp2FMiB_nuZ71A7VSniCPRYnUU6LeLrOXw

{
  "title": "Ushalmas orzular",
  "content": "Bu yerda eng ko'p xoxlangan orzular yashirin",
  "photo": {
    "photoId": "feb02e30-295f-47ca-b072-98b361f2676f.jpg"
  }
}

### GET PROFILE'S OWN POSTS
GET localhost:8080/api/v1/post/profile?page=1&size?3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxOGM2MjJhOC04ZTJjLTQ1MmUtYWJjOS1hYjk2MDUxZTVlNzQiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzY4MjI4LCJleHAiOjE3NDQ5NzMwMjh9.I2RFeL2dKAvJCx6xVLIm6lXfHoB1G7q55-JvwWS-ONRTBcuy35qUTp2FMiB_nuZ71A7VSniCPRYnUU6LeLrOXw

### GET FULL DETAILS OF A POST
GET localhost:8080/api/v1/post/public/218dc1c4-10a9-4183-9389-659cee43539b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxOGM2MjJhOC04ZTJjLTQ1MmUtYWJjOS1hYjk2MDUxZTVlNzQiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzY4MjI4LCJleHAiOjE3NDQ5NzMwMjh9.I2RFeL2dKAvJCx6xVLIm6lXfHoB1G7q55-JvwWS-ONRTBcuy35qUTp2FMiB_nuZ71A7VSniCPRYnUU6LeLrOXw

### UPDATE A POST
PUT localhost:8080/api/v1/post/218dc1c4-10a9-4183-9389-659cee43539b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiJkZTAwNzgyZi05YzM3LTRiMWMtOTIxZS1iZjI1YTEyOWEyNDciLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzJAZ21haWwuY29tIiwiaWF0IjoxNzQ0NTQ2OTkxLCJleHAiOjE3NDUxNTE3OTF9.IanJyVyBZ-2qPdBZIZoe5SKBAFRU41-8zYObXpwf9r0LhpmUBO5Gz8a1f-qdZxGw9i-6pCzObAI76RN0U68UjQ

{
  "title": "Ushalmas orzular",
  "content": "Bu yerda eng ko'p xoxlangan orzular yashiringan",
  "photo": {
    "photoId": "feb02e30-295f-47ca-b072-98b361f2676f.jpg"
  }
}

### DELETE A POST
DELETE localhost:8080/api/v1/post/218dc1c4-10a9-4183-9389-659cee43539b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxOGM2MjJhOC04ZTJjLTQ1MmUtYWJjOS1hYjk2MDUxZTVlNzQiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzQ0NTUzMzgwLCJleHAiOjE3NDUxNTgxODB9.eOSwexhcLvPFXJrXtJwR6vw9P7r9UXJ90xt1OuTECEdarSKE8HWmxYYgIFLYnEzJgyUbAKyo1UaKgfKJuRzjuA

### FILTER POSTS
POST localhost:8080/api/v1/post/public/filter?page=1&size=3
Content-Type: application/json

{
  "query": "scenery"
}

### GET SIMILAR POSTS
POST localhost:8080/api/v1/post/public/similar
Content-Type: application/json

{
  "exceptId": "8dd7fe5d-8d6c-4fba-92d4-893e433852b0"
}

### FILTER ADMIN POSTS
POST localhost:8080/api/v1/post/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjoiMWEyYjNjNGQtMDAwMS00ZTZmLThjMmYtMTExMTExMTExMTExIiwic3ViIjoib3J0aXFvdm11emFmZmFyMTcxQGdtYWlsLmNvbSIsImlhdCI6MTc0NzAzNDA0NCwiZXhwIjoxNzQ3NjM4ODQ0fQ.yodl39JvBekxLHFDvV1vTxr2MBeH3Awi16bvxy4KjEEI1PZeT1BVi0YLHd-UHBnqeqaEccYuZk4tuijxISIv5Q

{
  "profileQuery": "Muzaffar",
  "postQuery": null
}
