### Update profile name
PUT localhost:8080/api/v1/profile/detail
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDM4YmJlZS1iNmMxLTQxM2UtYjU3MS0yNGE0MmI4YjQ5ZWYiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzQwNDI2LCJleHAiOjE3Njk5NDUyMjZ9.OL2a6Kc_-hu8ckIB-A1rk0E70sd9HWCT1k4iYIcr82L4MMA2uWBlwIH-oJbWI1ZSYcFXPQ3YvHTGxzsRQBaiAg

{
  "name": "Raffazum"
}

### Update profile password
PUT localhost:8080/api/v1/profile/password
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDM4YmJlZS1iNmMxLTQxM2UtYjU3MS0yNGE0MmI4YjQ5ZWYiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzQwNDI2LCJleHAiOjE3Njk5NDUyMjZ9.OL2a6Kc_-hu8ckIB-A1rk0E70sd9HWCT1k4iYIcr82L4MMA2uWBlwIH-oJbWI1ZSYcFXPQ3YvHTGxzsRQBaiAg

{
  "currentPassword": "1234",
  "newPassword": "777"
}

### Update profile username
PUT localhost:8080/api/v1/profile/username
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDM4YmJlZS1iNmMxLTQxM2UtYjU3MS0yNGE0MmI4YjQ5ZWYiLCJzdWIiOiJtdXphZmZhcm9ydGlxb3YxOUBnbWFpbC5jb20iLCJpYXQiOjE3NjkzNDEwNTUsImV4cCI6MTc2OTk0NTg1NX0.I9XvQOVVrtGFbmapgXRFQgrDEPjMGVcm6IC61nl4u_vxmwZc5LMBvRcyg9e0l9w9It6qFH_dH9KzTbtQf2_0hQ

{
  "username": "ortiqovmuzaffar171@gmail.com"
}

### Update profile username confirm
PUT localhost:8080/api/v1/profile/username-confirmation
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDM4YmJlZS1iNmMxLTQxM2UtYjU3MS0yNGE0MmI4YjQ5ZWYiLCJzdWIiOiJtdXphZmZhcm9ydGlxb3YxOUBnbWFpbC5jb20iLCJpYXQiOjE3NjkzNDEwNTUsImV4cCI6MTc2OTk0NTg1NX0.I9XvQOVVrtGFbmapgXRFQgrDEPjMGVcm6IC61nl4u_vxmwZc5LMBvRcyg9e0l9w9It6qFH_dH9KzTbtQf2_0hQ

{
  "code": "93199"
}

### Update profile photo
PUT localhost:8080/api/v1/profile/photo
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaWQiOiIxMDM4YmJlZS1iNmMxLTQxM2UtYjU3MS0yNGE0MmI4YjQ5ZWYiLCJzdWIiOiJvcnRpcW92bXV6YWZmYXIxNzFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzQxMzAyLCJleHAiOjE3Njk5NDYxMDJ9.gjlklqPGrB_jDoaU9cxE8MTLtAtYsIbkBLiBgGCKztXr8w_UNhBVlVfVExjXGvAuhpSuVLCLw6G8NIywWD0F3Q

{
  "photoId": "136be57d-455c-4920-8fcc-d443fbf5e828.jpg"
}

### GET PROFILE LIST FILTER
POST localhost:8080/api/v1/profile/filter
Content-Type: application/json
Accept-Language: UZ
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjoiYmE3NjViMmItNTNlYi00MTBmLWE5MmMtY2E0NTE2ODFiYWUxIiwic3ViIjoibXV6YWZmYXJtaWtlMkBnbWFpbC5jb20iLCJpYXQiOjE3NjkzMzk0NjksImV4cCI6MTc2OTk0NDI2OX0.w30Y_VhqFdiT6bWlpm7TbF9qEuck6NbaeH1OBE7VPxarQscjpM0WptUC3qh-0OdXhsfhuQI8gzrMTW6Z860DPw

{
  "query": "Muza"
}

### CHANGE PROFILE STATUS
PUT localhost:8080/api/v1/profile/status/1038bbee-b6c1-413e-b571-24a42b8b49ef
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjoiYmE3NjViMmItNTNlYi00MTBmLWE5MmMtY2E0NTE2ODFiYWUxIiwic3ViIjoibXV6YWZmYXJtaWtlMkBnbWFpbC5jb20iLCJpYXQiOjE3NjkzMzk0NjksImV4cCI6MTc2OTk0NDI2OX0.w30Y_VhqFdiT6bWlpm7TbF9qEuck6NbaeH1OBE7VPxarQscjpM0WptUC3qh-0OdXhsfhuQI8gzrMTW6Z860DPw

{
  "status": "ACTIVE"
}

### DELETE PROFILE
DELETE localhost:8080/api/v1/profile/1038bbee-b6c1-413e-b571-24a42b8b49ef
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImlkIjoiYmE3NjViMmItNTNlYi00MTBmLWE5MmMtY2E0NTE2ODFiYWUxIiwic3ViIjoibXV6YWZmYXJtaWtlMkBnbWFpbC5jb20iLCJpYXQiOjE3NjkzMzk0NjksImV4cCI6MTc2OTk0NDI2OX0.w30Y_VhqFdiT6bWlpm7TbF9qEuck6NbaeH1OBE7VPxarQscjpM0WptUC3qh-0OdXhsfhuQI8gzrMTW6Z860DPw

